### PR TITLE
Made few improvements

### PR DESCRIPTION
**Pull request by batkov**
I've made few improvements based on your code. 
Pull it if you want. I want to improve original pod, but looks like @hackiftekhar doesn't want to.

### CODE REVIEW

**Comment by sebastianludwig** [comment]
Thank you very much for this PR! I'm about to embark on a three month backpacking trip tomorrow. Not sure when and if I'll be able to look into this again - depends on my mood and the wi-fi ;-)

**Comment by batkov** [comment]
Great. Let me know if you'll made some changes. I would like to use improvements too.

**Comment by sebastianludwig** [comment]
Hey, sorry for the delay. I got around to take a closer look at the library and your PR. Thank you very much for your work, I highly appreciate it! However I won't be able to merge your PR due to the recent refactorings I made and the open issues (see comments to commits). However I'll include your improvements manually. Please feedback what your think on the commits on my master branch.

**Comment by sebastianludwig** [comment]
Thank you very much again for all your work! In the end I decided agains merging your PR, but incorporated all your features nevertheless. I hope you can work with it this way as well. Any feedback highly appreciated! So let me know what you think, if you've got the time.

**Pull request closed without merging**
